-- EXERCISE

INSERT INTO EMPLOYEE VALUES('Matt','C','Johnson',231342904,'1985-01-02','331 Fondren, Housten, TX','M', 34000,'333445555',5);

GRANT CREATE VIEW ON company_security.* TO 'user1'@'localhost';
GRANT SELECT ON company_security.WORKS_ON TO 'user1'@'localhost';

CREATE VIEW WORKS_ON1 AS SELECT Fname, Lname, Pno FROM Employee JOIN WORKS_ON ON Ssn=Essn;

CREATE USER 'user2'@'localhost' IDENTIFIED BY 'password2';

GRANT SELECT ON company_security.WORKS_ON1 TO 'user2'@'localhost';

SELECT * FROM WORKS_ON1;

SELECT * FROM Employee;
SELECT * FROM WORKS_ON;

REVOKE ALL PRIVILEGES ON company_security.WORKS_ON FROM 'user1'@'localhost';
REVOKE ALL PRIVILEGES ON company_security.EMPLOYEE FROM 'user1'@'localhost';

SELECT * FROM WORKS_ON1;
SHOW GRANTS;

-- SQL INJECTION ATTACKS

SELECT * FROM EMPLOYEE WHERE ssn = '999887777';
SELECT * FROM EMPLOYEE WHERE ssn = '999887777' OR 'x'= 'x';

-- ASSIGNMENT

CREATE USER 'A'@'localhost' IDENTIFIED BY 'pw1';
CREATE USER 'B'@'localhost' IDENTIFIED BY 'pw2';
CREATE USER 'C'@'localhost' IDENTIFIED BY 'pw3';
CREATE USER 'D'@'localhost' IDENTIFIED BY 'pw4';
CREATE USER 'E'@'localhost' IDENTIFIED BY 'pw5';

GRANT SELECT, INSERT, UPDATE, DELETE ON EMPLOYEE TO 'A'@'localhost' WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON DEPARTMENT TO 'A'@'localhost' WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON DEPT_LOCATIONS TO 'A'@'localhost' WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON PROJECT TO 'A'@'localhost' WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE ON WORKS_ON TO 'A'@'localhost' WITH GRANT OPTION;

CREATE VIEW EMPLOYEE_B AS SELECT Fname,Minit,Lname, Ssn, Bdate, Address, Sex, Super_ssn, Dno FROM EMPLOYEE;
GRANT SELECT ON EMPLOYEE_B TO 'B'@'localhost';
CREATE VIEW DEPARTMENT_B AS SELECT Dname, Dnumber FROM DEPARTMENT;
GRANT SELECT ON DEPARTMENT_B TO 'B'@'localhost';

GRANT SELECT, INSERT, UPDATE, DELETE ON WORKS_ON TO 'C'@'localhost';
CREATE VIEW EMPLOYEE_C AS SELECT Fname, Minit, Lname, Ssn FROM EMPLOYEE;
GRANT SELECT ON EMPLOYEE_C TO 'C'@'localhost';
CREATE VIEW PROJECT_C AS SELECT Pname, Pnumber FROM PROJECT;
GRANT SELECT ON PROJECT_C TO 'C'@'localhost';

GRANT SELECT ON EMPLOYEE TO 'D'@'localhost';
GRANT SELECT, INSERT, UPDATE, DELETE ON DEPENDENT TO 'D'@'localhost'; 

CREATE VIEW EMPLOYEE_E AS SELECT * FROM EMPLOYEE WHERE Dno = 3;
GRANT SELECT ON EMPLOYEE_E TO 'E'@'localhost';